### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ASTAR123** [ilkyyldz95/EEG_MVTS#2]
How to get dataset? Do I need to apply for qualifications?

**Comment by ilkyyldz95** [comment]
Thank you for your interest!

TUH dataset is available here, please follow instructions for TUSZ: https://isip.piconepress.com/projects/tuh_eeg/html/downloads.shtml  

MIT dataset is available here: https://physionet.org/content/chbmit/1.0.0/

UPenn dataset is available here: https://www.kaggle.com/competitions/seizure-detection

After downloading, you can follow the preprocessing instructions in the README.
