### ISSUE TITLE
Concatenate attention weights

### ISSUE THREAD

**Issue by elisaparga19** [ilkyyldz95/EEG_MVTS#3]
Hello!

I'm adapting your work for anomaly detection in ECGs :)
I just have one question with respect to the forward method of the TSTransformerEncoder. Why in the end you concatenate the output with the attention weights?

Thanks in advance!

Elisa.

**Comment by ilkyyldz95** [comment]
Thank you for your interest! I only concatenated attention weights for plotting examples of attention over input windows later in running.py evaluate method. Attention is removed from the real output in all anomaly detection / seizure identification calculations.
